/home/tsb/.local/lib/python3.10/site-packages/webdataset/compat.py:136: UserWarning: WebDataset(shardshuffle=...) is None; set explicitly to False or a number
  warnings.warn("WebDataset(shardshuffle=...) is None; set explicitly to False or a number")
Exception in thread Thread-4 (_loader_worker):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tsb/.local/lib/python3.10/site-packages/torch_xla/distributed/parallel_loader.py", line 156, in _loader_worker
    _, data = next(data_iter)
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/tsb/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 42, in fetch
    data = next(self.dataset_iter)
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/pipeline.py", line 71, in iterator
    for sample in self.iterator1():
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 490, in _batched
    for sample in data:
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 305, in _map
    for sample in data:
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 409, in _to_tuple
    if handler(exn):
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 86, in reraise_exception
    raise exn
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 402, in _to_tuple
    result = tuple(
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 403, in <genexpr>
    getfirst(sample, f, missing_is_error=missing_is_error) for f in args
  File "/home/tsb/.local/lib/python3.10/site-packages/webdataset/filters.py", line 123, in getfirst
    raise ValueError(f"didn't find {keys} in {list(a.keys())}")
ValueError: didn't find ['jpeg'] in ['__key__', '__url__', 'jpg', '__local_path__', 'json', 'txt']
